name: 'Build Jekyll for GitHub Pages (Composite)'
description: 'A simple GitHub Action for producing Jekyll build artifacts compatible with GitHub Pages'
author: 'GitHub'
inputs:
  source:
    description: 'Directory where the source files reside.'
    required: false
    default: ./
  destination:
    description: 'Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.'
    required: false
    default: ./_site
  future:
    description: 'Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.'
    required: false
    default: false
  build_revision:
    description: 'The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.'
    required: false
    default: ${{ github.sha }}
  verbose:
    description: 'Verbose output'
    required: false
    default: true
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Check GHCR status
      id: ghcr
      # using an internal endpoint would be better than status page
      # but this is an acceptable starting point
      run: |
        packagesStatus=$(curl -LSs https://www.githubstatus.com/api/v2/components.json | jq -r '.components[] | select(.name == "Packages") | .status')
        echo status=$packagesStatus >> $GITHUB_OUTPUT

    - if: ${{ steps.ghcr.outputs.status == 'operational' }}
      # load another composite action that pulls `docker://ghcr.io/...`
      #uses: paper-spa/jekyll-build-pages/composite-docker-ghcr@v1.0.7
      uses: paper-spa/jekyll-build-pages/composite-docker-ghcr@main
      with:
        source: ${{ inputs.source }}
        destination: ${{ inputs.destination }}
        future: ${{ inputs.future }}
        build_revision: ${{ inputs.build_revision }}
        verbose: ${{ inputs.verbose }}
        token: ${{ inputs.token }}

    - if: ${{ steps.ghcr.outputs.status != 'operational' }}
      # load another composite action that builds the Docker image locally
      #uses: paper-spa/jekyll-build-pages/composite-docker-local@v1.0.7
      uses: paper-spa/jekyll-build-pages/composite-docker-local@main
      with:
        source: ${{ inputs.source }}
        destination: ${{ inputs.destination }}
        future: ${{ inputs.future }}
        build_revision: ${{ inputs.build_revision }}
        verbose: ${{ inputs.verbose }}
        token: ${{ inputs.token }}
